/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthVerificationIndexImport } from './routes/auth/verification/index'
import { Route as AuthRequestIndexImport } from './routes/auth/request/index'
import { Route as AuthPasswordResetIndexImport } from './routes/auth/password-reset/index'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as AuthForgotPasswordIndexImport } from './routes/auth/forgot-password/index'
import { Route as AuthenticatedWalletIndexImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedWalletFundingImport } from './routes/_authenticated/wallet/funding'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMessagingSmsImport } from './routes/_authenticated/messaging/sms'
import { Route as AuthenticatedAdminUsersImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedZoneCellsIndexImport } from './routes/_authenticated/zone/cells/index'
import { Route as AuthenticatedZoneAttendanceIndexImport } from './routes/_authenticated/zone/attendance/index'
import { Route as AuthenticatedMessagingPhoneBookIndexImport } from './routes/_authenticated/messaging/phone-book/index'
import { Route as AuthenticatedCellMembersIndexImport } from './routes/_authenticated/cell/members/index'
import { Route as AuthenticatedCellAttendanceIndexImport } from './routes/_authenticated/cell/attendance/index'
import { Route as AuthenticatedAdminZonesIndexImport } from './routes/_authenticated/admin/zones/index'
import { Route as AuthenticatedZoneCellsCellIdImport } from './routes/_authenticated/zone/cells/$cellId'
import { Route as AuthenticatedMessagingPhoneBookPhonebookIdImport } from './routes/_authenticated/messaging/phone-book/$phonebookId'
import { Route as AuthenticatedCellAttendanceCellAttendanceCellIdImport } from './routes/_authenticated/cell/attendance/$cellAttendanceCellId'
import { Route as AuthenticatedAdminRequestsActionsImport } from './routes/_authenticated/admin/requests/actions'
import { Route as AuthenticatedAdminRequestsAccessImport } from './routes/_authenticated/admin/requests/access'
import { Route as AuthenticatedAdminZonesAttendanceIndexImport } from './routes/_authenticated/admin/zones/attendance/index'
import { Route as AuthenticatedAdminZonesZoneIdIndexImport } from './routes/_authenticated/admin/zones/$zoneId/index'
import { Route as AuthenticatedAdminZonesZoneIdCellIdImport } from './routes/_authenticated/admin/zones/$zoneId/$cellId'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthVerificationIndexRoute = AuthVerificationIndexImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthRequestIndexRoute = AuthRequestIndexImport.update({
  id: '/request/',
  path: '/request/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthPasswordResetIndexRoute = AuthPasswordResetIndexImport.update({
  id: '/password-reset/',
  path: '/password-reset/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthenticatedWalletIndexRoute = AuthenticatedWalletIndexImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedWalletFundingRoute = AuthenticatedWalletFundingImport.update(
  {
    id: '/wallet/funding',
    path: '/wallet/funding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedMessagingSmsRoute = AuthenticatedMessagingSmsImport.update({
  id: '/messaging/sms',
  path: '/messaging/sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedZoneCellsIndexRoute =
  AuthenticatedZoneCellsIndexImport.update({
    id: '/zone/cells/',
    path: '/zone/cells/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedZoneAttendanceIndexRoute =
  AuthenticatedZoneAttendanceIndexImport.update({
    id: '/zone/attendance/',
    path: '/zone/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMessagingPhoneBookIndexRoute =
  AuthenticatedMessagingPhoneBookIndexImport.update({
    id: '/messaging/phone-book/',
    path: '/messaging/phone-book/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCellMembersIndexRoute =
  AuthenticatedCellMembersIndexImport.update({
    id: '/cell/members/',
    path: '/cell/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCellAttendanceIndexRoute =
  AuthenticatedCellAttendanceIndexImport.update({
    id: '/cell/attendance/',
    path: '/cell/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminZonesIndexRoute =
  AuthenticatedAdminZonesIndexImport.update({
    id: '/admin/zones/',
    path: '/admin/zones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedZoneCellsCellIdRoute =
  AuthenticatedZoneCellsCellIdImport.update({
    id: '/zone/cells/$cellId',
    path: '/zone/cells/$cellId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMessagingPhoneBookPhonebookIdRoute =
  AuthenticatedMessagingPhoneBookPhonebookIdImport.update({
    id: '/messaging/phone-book/$phonebookId',
    path: '/messaging/phone-book/$phonebookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCellAttendanceCellAttendanceCellIdRoute =
  AuthenticatedCellAttendanceCellAttendanceCellIdImport.update({
    id: '/cell/attendance/$cellAttendanceCellId',
    path: '/cell/attendance/$cellAttendanceCellId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminRequestsActionsRoute =
  AuthenticatedAdminRequestsActionsImport.update({
    id: '/admin/requests/actions',
    path: '/admin/requests/actions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminRequestsAccessRoute =
  AuthenticatedAdminRequestsAccessImport.update({
    id: '/admin/requests/access',
    path: '/admin/requests/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminZonesAttendanceIndexRoute =
  AuthenticatedAdminZonesAttendanceIndexImport.update({
    id: '/admin/zones/attendance/',
    path: '/admin/zones/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminZonesZoneIdIndexRoute =
  AuthenticatedAdminZonesZoneIdIndexImport.update({
    id: '/admin/zones/$zoneId/',
    path: '/admin/zones/$zoneId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAdminZonesZoneIdCellIdRoute =
  AuthenticatedAdminZonesZoneIdCellIdImport.update({
    id: '/admin/zones/$zoneId/$cellId',
    path: '/admin/zones/$zoneId/$cellId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/messaging/sms': {
      id: '/_authenticated/messaging/sms'
      path: '/messaging/sms'
      fullPath: '/messaging/sms'
      preLoaderRoute: typeof AuthenticatedMessagingSmsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/wallet/funding': {
      id: '/_authenticated/wallet/funding'
      path: '/wallet/funding'
      fullPath: '/wallet/funding'
      preLoaderRoute: typeof AuthenticatedWalletFundingImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/password-reset/': {
      id: '/auth/password-reset/'
      path: '/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/request/': {
      id: '/auth/request/'
      path: '/request'
      fullPath: '/auth/request'
      preLoaderRoute: typeof AuthRequestIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/verification/': {
      id: '/auth/verification/'
      path: '/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_authenticated/admin/requests/access': {
      id: '/_authenticated/admin/requests/access'
      path: '/admin/requests/access'
      fullPath: '/admin/requests/access'
      preLoaderRoute: typeof AuthenticatedAdminRequestsAccessImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/requests/actions': {
      id: '/_authenticated/admin/requests/actions'
      path: '/admin/requests/actions'
      fullPath: '/admin/requests/actions'
      preLoaderRoute: typeof AuthenticatedAdminRequestsActionsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/cell/attendance/$cellAttendanceCellId': {
      id: '/_authenticated/cell/attendance/$cellAttendanceCellId'
      path: '/cell/attendance/$cellAttendanceCellId'
      fullPath: '/cell/attendance/$cellAttendanceCellId'
      preLoaderRoute: typeof AuthenticatedCellAttendanceCellAttendanceCellIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/messaging/phone-book/$phonebookId': {
      id: '/_authenticated/messaging/phone-book/$phonebookId'
      path: '/messaging/phone-book/$phonebookId'
      fullPath: '/messaging/phone-book/$phonebookId'
      preLoaderRoute: typeof AuthenticatedMessagingPhoneBookPhonebookIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/zone/cells/$cellId': {
      id: '/_authenticated/zone/cells/$cellId'
      path: '/zone/cells/$cellId'
      fullPath: '/zone/cells/$cellId'
      preLoaderRoute: typeof AuthenticatedZoneCellsCellIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/zones/': {
      id: '/_authenticated/admin/zones/'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/cell/attendance/': {
      id: '/_authenticated/cell/attendance/'
      path: '/cell/attendance'
      fullPath: '/cell/attendance'
      preLoaderRoute: typeof AuthenticatedCellAttendanceIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/cell/members/': {
      id: '/_authenticated/cell/members/'
      path: '/cell/members'
      fullPath: '/cell/members'
      preLoaderRoute: typeof AuthenticatedCellMembersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/messaging/phone-book/': {
      id: '/_authenticated/messaging/phone-book/'
      path: '/messaging/phone-book'
      fullPath: '/messaging/phone-book'
      preLoaderRoute: typeof AuthenticatedMessagingPhoneBookIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/zone/attendance/': {
      id: '/_authenticated/zone/attendance/'
      path: '/zone/attendance'
      fullPath: '/zone/attendance'
      preLoaderRoute: typeof AuthenticatedZoneAttendanceIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/zone/cells/': {
      id: '/_authenticated/zone/cells/'
      path: '/zone/cells'
      fullPath: '/zone/cells'
      preLoaderRoute: typeof AuthenticatedZoneCellsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/zones/$zoneId/$cellId': {
      id: '/_authenticated/admin/zones/$zoneId/$cellId'
      path: '/admin/zones/$zoneId/$cellId'
      fullPath: '/admin/zones/$zoneId/$cellId'
      preLoaderRoute: typeof AuthenticatedAdminZonesZoneIdCellIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/zones/$zoneId/': {
      id: '/_authenticated/admin/zones/$zoneId/'
      path: '/admin/zones/$zoneId'
      fullPath: '/admin/zones/$zoneId'
      preLoaderRoute: typeof AuthenticatedAdminZonesZoneIdIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/zones/attendance/': {
      id: '/_authenticated/admin/zones/attendance/'
      path: '/admin/zones/attendance'
      fullPath: '/admin/zones/attendance'
      preLoaderRoute: typeof AuthenticatedAdminZonesAttendanceIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedMessagingSmsRoute: typeof AuthenticatedMessagingSmsRoute
  AuthenticatedWalletFundingRoute: typeof AuthenticatedWalletFundingRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
  AuthenticatedAdminRequestsAccessRoute: typeof AuthenticatedAdminRequestsAccessRoute
  AuthenticatedAdminRequestsActionsRoute: typeof AuthenticatedAdminRequestsActionsRoute
  AuthenticatedCellAttendanceCellAttendanceCellIdRoute: typeof AuthenticatedCellAttendanceCellAttendanceCellIdRoute
  AuthenticatedMessagingPhoneBookPhonebookIdRoute: typeof AuthenticatedMessagingPhoneBookPhonebookIdRoute
  AuthenticatedZoneCellsCellIdRoute: typeof AuthenticatedZoneCellsCellIdRoute
  AuthenticatedAdminZonesIndexRoute: typeof AuthenticatedAdminZonesIndexRoute
  AuthenticatedCellAttendanceIndexRoute: typeof AuthenticatedCellAttendanceIndexRoute
  AuthenticatedCellMembersIndexRoute: typeof AuthenticatedCellMembersIndexRoute
  AuthenticatedMessagingPhoneBookIndexRoute: typeof AuthenticatedMessagingPhoneBookIndexRoute
  AuthenticatedZoneAttendanceIndexRoute: typeof AuthenticatedZoneAttendanceIndexRoute
  AuthenticatedZoneCellsIndexRoute: typeof AuthenticatedZoneCellsIndexRoute
  AuthenticatedAdminZonesZoneIdCellIdRoute: typeof AuthenticatedAdminZonesZoneIdCellIdRoute
  AuthenticatedAdminZonesZoneIdIndexRoute: typeof AuthenticatedAdminZonesZoneIdIndexRoute
  AuthenticatedAdminZonesAttendanceIndexRoute: typeof AuthenticatedAdminZonesAttendanceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedMessagingSmsRoute: AuthenticatedMessagingSmsRoute,
  AuthenticatedWalletFundingRoute: AuthenticatedWalletFundingRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
  AuthenticatedAdminRequestsAccessRoute: AuthenticatedAdminRequestsAccessRoute,
  AuthenticatedAdminRequestsActionsRoute:
    AuthenticatedAdminRequestsActionsRoute,
  AuthenticatedCellAttendanceCellAttendanceCellIdRoute:
    AuthenticatedCellAttendanceCellAttendanceCellIdRoute,
  AuthenticatedMessagingPhoneBookPhonebookIdRoute:
    AuthenticatedMessagingPhoneBookPhonebookIdRoute,
  AuthenticatedZoneCellsCellIdRoute: AuthenticatedZoneCellsCellIdRoute,
  AuthenticatedAdminZonesIndexRoute: AuthenticatedAdminZonesIndexRoute,
  AuthenticatedCellAttendanceIndexRoute: AuthenticatedCellAttendanceIndexRoute,
  AuthenticatedCellMembersIndexRoute: AuthenticatedCellMembersIndexRoute,
  AuthenticatedMessagingPhoneBookIndexRoute:
    AuthenticatedMessagingPhoneBookIndexRoute,
  AuthenticatedZoneAttendanceIndexRoute: AuthenticatedZoneAttendanceIndexRoute,
  AuthenticatedZoneCellsIndexRoute: AuthenticatedZoneCellsIndexRoute,
  AuthenticatedAdminZonesZoneIdCellIdRoute:
    AuthenticatedAdminZonesZoneIdCellIdRoute,
  AuthenticatedAdminZonesZoneIdIndexRoute:
    AuthenticatedAdminZonesZoneIdIndexRoute,
  AuthenticatedAdminZonesAttendanceIndexRoute:
    AuthenticatedAdminZonesAttendanceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthPasswordResetIndexRoute: typeof AuthPasswordResetIndexRoute
  AuthRequestIndexRoute: typeof AuthRequestIndexRoute
  AuthVerificationIndexRoute: typeof AuthVerificationIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthPasswordResetIndexRoute: AuthPasswordResetIndexRoute,
  AuthRequestIndexRoute: AuthRequestIndexRoute,
  AuthVerificationIndexRoute: AuthVerificationIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/messaging/sms': typeof AuthenticatedMessagingSmsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/wallet/funding': typeof AuthenticatedWalletFundingRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/password-reset': typeof AuthPasswordResetIndexRoute
  '/auth/request': typeof AuthRequestIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/admin/requests/access': typeof AuthenticatedAdminRequestsAccessRoute
  '/admin/requests/actions': typeof AuthenticatedAdminRequestsActionsRoute
  '/cell/attendance/$cellAttendanceCellId': typeof AuthenticatedCellAttendanceCellAttendanceCellIdRoute
  '/messaging/phone-book/$phonebookId': typeof AuthenticatedMessagingPhoneBookPhonebookIdRoute
  '/zone/cells/$cellId': typeof AuthenticatedZoneCellsCellIdRoute
  '/admin/zones': typeof AuthenticatedAdminZonesIndexRoute
  '/cell/attendance': typeof AuthenticatedCellAttendanceIndexRoute
  '/cell/members': typeof AuthenticatedCellMembersIndexRoute
  '/messaging/phone-book': typeof AuthenticatedMessagingPhoneBookIndexRoute
  '/zone/attendance': typeof AuthenticatedZoneAttendanceIndexRoute
  '/zone/cells': typeof AuthenticatedZoneCellsIndexRoute
  '/admin/zones/$zoneId/$cellId': typeof AuthenticatedAdminZonesZoneIdCellIdRoute
  '/admin/zones/$zoneId': typeof AuthenticatedAdminZonesZoneIdIndexRoute
  '/admin/zones/attendance': typeof AuthenticatedAdminZonesAttendanceIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/messaging/sms': typeof AuthenticatedMessagingSmsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/wallet/funding': typeof AuthenticatedWalletFundingRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/password-reset': typeof AuthPasswordResetIndexRoute
  '/auth/request': typeof AuthRequestIndexRoute
  '/auth/verification': typeof AuthVerificationIndexRoute
  '/admin/requests/access': typeof AuthenticatedAdminRequestsAccessRoute
  '/admin/requests/actions': typeof AuthenticatedAdminRequestsActionsRoute
  '/cell/attendance/$cellAttendanceCellId': typeof AuthenticatedCellAttendanceCellAttendanceCellIdRoute
  '/messaging/phone-book/$phonebookId': typeof AuthenticatedMessagingPhoneBookPhonebookIdRoute
  '/zone/cells/$cellId': typeof AuthenticatedZoneCellsCellIdRoute
  '/admin/zones': typeof AuthenticatedAdminZonesIndexRoute
  '/cell/attendance': typeof AuthenticatedCellAttendanceIndexRoute
  '/cell/members': typeof AuthenticatedCellMembersIndexRoute
  '/messaging/phone-book': typeof AuthenticatedMessagingPhoneBookIndexRoute
  '/zone/attendance': typeof AuthenticatedZoneAttendanceIndexRoute
  '/zone/cells': typeof AuthenticatedZoneCellsIndexRoute
  '/admin/zones/$zoneId/$cellId': typeof AuthenticatedAdminZonesZoneIdCellIdRoute
  '/admin/zones/$zoneId': typeof AuthenticatedAdminZonesZoneIdIndexRoute
  '/admin/zones/attendance': typeof AuthenticatedAdminZonesAttendanceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/messaging/sms': typeof AuthenticatedMessagingSmsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/wallet/funding': typeof AuthenticatedWalletFundingRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/password-reset/': typeof AuthPasswordResetIndexRoute
  '/auth/request/': typeof AuthRequestIndexRoute
  '/auth/verification/': typeof AuthVerificationIndexRoute
  '/_authenticated/admin/requests/access': typeof AuthenticatedAdminRequestsAccessRoute
  '/_authenticated/admin/requests/actions': typeof AuthenticatedAdminRequestsActionsRoute
  '/_authenticated/cell/attendance/$cellAttendanceCellId': typeof AuthenticatedCellAttendanceCellAttendanceCellIdRoute
  '/_authenticated/messaging/phone-book/$phonebookId': typeof AuthenticatedMessagingPhoneBookPhonebookIdRoute
  '/_authenticated/zone/cells/$cellId': typeof AuthenticatedZoneCellsCellIdRoute
  '/_authenticated/admin/zones/': typeof AuthenticatedAdminZonesIndexRoute
  '/_authenticated/cell/attendance/': typeof AuthenticatedCellAttendanceIndexRoute
  '/_authenticated/cell/members/': typeof AuthenticatedCellMembersIndexRoute
  '/_authenticated/messaging/phone-book/': typeof AuthenticatedMessagingPhoneBookIndexRoute
  '/_authenticated/zone/attendance/': typeof AuthenticatedZoneAttendanceIndexRoute
  '/_authenticated/zone/cells/': typeof AuthenticatedZoneCellsIndexRoute
  '/_authenticated/admin/zones/$zoneId/$cellId': typeof AuthenticatedAdminZonesZoneIdCellIdRoute
  '/_authenticated/admin/zones/$zoneId/': typeof AuthenticatedAdminZonesZoneIdIndexRoute
  '/_authenticated/admin/zones/attendance/': typeof AuthenticatedAdminZonesAttendanceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/messaging/sms'
    | '/settings/account'
    | '/wallet/funding'
    | '/settings/'
    | '/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/request'
    | '/auth/verification'
    | '/admin/requests/access'
    | '/admin/requests/actions'
    | '/cell/attendance/$cellAttendanceCellId'
    | '/messaging/phone-book/$phonebookId'
    | '/zone/cells/$cellId'
    | '/admin/zones'
    | '/cell/attendance'
    | '/cell/members'
    | '/messaging/phone-book'
    | '/zone/attendance'
    | '/zone/cells'
    | '/admin/zones/$zoneId/$cellId'
    | '/admin/zones/$zoneId'
    | '/admin/zones/attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/users'
    | '/messaging/sms'
    | '/settings/account'
    | '/wallet/funding'
    | '/settings'
    | '/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/request'
    | '/auth/verification'
    | '/admin/requests/access'
    | '/admin/requests/actions'
    | '/cell/attendance/$cellAttendanceCellId'
    | '/messaging/phone-book/$phonebookId'
    | '/zone/cells/$cellId'
    | '/admin/zones'
    | '/cell/attendance'
    | '/cell/members'
    | '/messaging/phone-book'
    | '/zone/attendance'
    | '/zone/cells'
    | '/admin/zones/$zoneId/$cellId'
    | '/admin/zones/$zoneId'
    | '/admin/zones/attendance'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/users'
    | '/_authenticated/messaging/sms'
    | '/_authenticated/settings/account'
    | '/_authenticated/wallet/funding'
    | '/_authenticated/settings/'
    | '/_authenticated/wallet/'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/password-reset/'
    | '/auth/request/'
    | '/auth/verification/'
    | '/_authenticated/admin/requests/access'
    | '/_authenticated/admin/requests/actions'
    | '/_authenticated/cell/attendance/$cellAttendanceCellId'
    | '/_authenticated/messaging/phone-book/$phonebookId'
    | '/_authenticated/zone/cells/$cellId'
    | '/_authenticated/admin/zones/'
    | '/_authenticated/cell/attendance/'
    | '/_authenticated/cell/members/'
    | '/_authenticated/messaging/phone-book/'
    | '/_authenticated/zone/attendance/'
    | '/_authenticated/zone/cells/'
    | '/_authenticated/admin/zones/$zoneId/$cellId'
    | '/_authenticated/admin/zones/$zoneId/'
    | '/_authenticated/admin/zones/attendance/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/admin/users",
        "/_authenticated/messaging/sms",
        "/_authenticated/wallet/funding",
        "/_authenticated/wallet/",
        "/_authenticated/admin/requests/access",
        "/_authenticated/admin/requests/actions",
        "/_authenticated/cell/attendance/$cellAttendanceCellId",
        "/_authenticated/messaging/phone-book/$phonebookId",
        "/_authenticated/zone/cells/$cellId",
        "/_authenticated/admin/zones/",
        "/_authenticated/cell/attendance/",
        "/_authenticated/cell/members/",
        "/_authenticated/messaging/phone-book/",
        "/_authenticated/zone/attendance/",
        "/_authenticated/zone/cells/",
        "/_authenticated/admin/zones/$zoneId/$cellId",
        "/_authenticated/admin/zones/$zoneId/",
        "/_authenticated/admin/zones/attendance/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password/",
        "/auth/login/",
        "/auth/password-reset/",
        "/auth/request/",
        "/auth/verification/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/users": {
      "filePath": "_authenticated/admin/users.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messaging/sms": {
      "filePath": "_authenticated/messaging/sms.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/wallet/funding": {
      "filePath": "_authenticated/wallet/funding.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/wallet/": {
      "filePath": "_authenticated/wallet/index.tsx",
      "parent": "/_authenticated"
    },
    "/auth/forgot-password/": {
      "filePath": "auth/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/password-reset/": {
      "filePath": "auth/password-reset/index.tsx",
      "parent": "/auth"
    },
    "/auth/request/": {
      "filePath": "auth/request/index.tsx",
      "parent": "/auth"
    },
    "/auth/verification/": {
      "filePath": "auth/verification/index.tsx",
      "parent": "/auth"
    },
    "/_authenticated/admin/requests/access": {
      "filePath": "_authenticated/admin/requests/access.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/requests/actions": {
      "filePath": "_authenticated/admin/requests/actions.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cell/attendance/$cellAttendanceCellId": {
      "filePath": "_authenticated/cell/attendance/$cellAttendanceCellId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messaging/phone-book/$phonebookId": {
      "filePath": "_authenticated/messaging/phone-book/$phonebookId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/zone/cells/$cellId": {
      "filePath": "_authenticated/zone/cells/$cellId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/zones/": {
      "filePath": "_authenticated/admin/zones/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cell/attendance/": {
      "filePath": "_authenticated/cell/attendance/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cell/members/": {
      "filePath": "_authenticated/cell/members/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messaging/phone-book/": {
      "filePath": "_authenticated/messaging/phone-book/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/zone/attendance/": {
      "filePath": "_authenticated/zone/attendance/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/zone/cells/": {
      "filePath": "_authenticated/zone/cells/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/zones/$zoneId/$cellId": {
      "filePath": "_authenticated/admin/zones/$zoneId/$cellId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/zones/$zoneId/": {
      "filePath": "_authenticated/admin/zones/$zoneId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/zones/attendance/": {
      "filePath": "_authenticated/admin/zones/attendance/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
